# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_date', models.DateTimeField()),
                ('pan_price', models.IntegerField()),
                ('pan_type', models.CharField(choices=[('01', 'Cash'), ('02', 'Credit'), ('03', 'Preorder')], max_length=2)),
                ('pan_end', models.CharField(default='N', max_length=1)),
            ],
        ),
    ]
